#Creating a deployment object from a custom tomcat
apiVersion: apps/v1
kind: Deployment
metadata:
 name: paresh-deploy
 labels:
  app: paresh-tom
spec:
 replicas: 5
 selector:
  matchLabels:
    app: paresh-tom
    tier: frontend
    env: prod
 template:
  metadata:
   name: pareshapp
   labels:
    app: paresh-tom
    tier: frontend
    env: prod
  spec:
   containers:
   - name: tomcat-container
     image: docker.io/pareshkaps/learning_devops:tomcat
     ports:
     - containerPort: 8080
